
# #   TO JUST COPY ONE FILE COMMAND IS THIS 
# #   args: ['gcloud', 'compute', 'scp', 'file1.txt', '$_VM_PATH', '--zone=$_ZONE']
# #    TO COPY WHOLE REPO COMMAND IS THIS
#   args: ['gcloud', 'compute', 'scp', '--recurse', 'testrepo', 'basic-vm:/home/shubhamv0205/pipelinedir', '--zone=us-central1-a']


steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash' 
#   args: ['gcloud', 'compute', 'scp', 'file1.txt', 'shubhamv0205@basic-vm:/home/shubhamv0205/pipelinedir', '--zone=us-central1-a']
  args: ['gcloud', 'compute', 'scp', 'script2.sh', 'shubhamv0205@basic-vm:/home/shubhamv0205/pipelinedir', '--zone=us-central1-a']

logsBucket: '$_BUCKET_LOGS'
serviceAccount: 'projects/$_PROJECT_ID/serviceAccounts/$_SERVICE_ACCOUNT'
options:
  logging: GCS_ONLY

# logsBucket: '$_BUCKET_LOGS'
# serviceAccount: 'projects/$_PROJECT_ID/serviceAccounts/$_SERVICE_ACCOUNT'
# options:
#   logging: GCS_ONLY
